/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author Shivam
 */
public class calculator extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     */
    
    double firstNum;
    double secondNum;
    double result;
    String Operations;
    
    public calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtDisplay = new javax.swing.JTextField();
        jBtnEight = new javax.swing.JButton();
        jBtnSeven = new javax.swing.JButton();
        jBtnFive = new javax.swing.JButton();
        jBtnFour = new javax.swing.JButton();
        jBtnTwo = new javax.swing.JButton();
        jBtnOne = new javax.swing.JButton();
        jBtnPlusMinus = new javax.swing.JButton();
        jBtnZero = new javax.swing.JButton();
        jBtnMinus = new javax.swing.JButton();
        jBtnNine = new javax.swing.JButton();
        jBtnPlus = new javax.swing.JButton();
        jBtnSix = new javax.swing.JButton();
        jBtnMul = new javax.swing.JButton();
        jBtnThree = new javax.swing.JButton();
        jBtnEquals = new javax.swing.JButton();
        jBtnDot = new javax.swing.JButton();
        jBtnClear = new javax.swing.JButton();
        jBtnBack = new javax.swing.JButton();
        jBtnDiv = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtDisplay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 50));

        jBtnEight.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEight.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnEight.setText("8");
        jBtnEight.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnEightAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEightActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEight, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 50, 50));

        jBtnSeven.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSeven.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnSeven.setText("7");
        jBtnSeven.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnSevenAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSevenActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSeven, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 50));

        jBtnFive.setBackground(new java.awt.Color(255, 255, 255));
        jBtnFive.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnFive.setText("5");
        jBtnFive.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnFiveAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFiveActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnFive, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 50, 50));

        jBtnFour.setBackground(new java.awt.Color(255, 255, 255));
        jBtnFour.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnFour.setText("4");
        jBtnFour.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnFourAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFourActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnFour, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 50));

        jBtnTwo.setBackground(new java.awt.Color(255, 255, 255));
        jBtnTwo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnTwo.setText("2");
        jBtnTwo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnTwoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTwoActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 50, 50));

        jBtnOne.setBackground(new java.awt.Color(255, 255, 255));
        jBtnOne.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnOne.setText("1");
        jBtnOne.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnOneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOneActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 50, 50));

        jBtnPlusMinus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnPlusMinus.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBtnPlusMinus.setText("+/-");
        jBtnPlusMinus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnPlusMinusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 50, 50));

        jBtnZero.setBackground(new java.awt.Color(255, 255, 255));
        jBtnZero.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnZero.setText("0");
        jBtnZero.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnZeroAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZeroActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnZero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 50, 50));

        jBtnMinus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnMinus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnMinus.setText("-");
        jBtnMinus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnMinusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMinusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 50, 50));

        jBtnNine.setBackground(new java.awt.Color(255, 255, 255));
        jBtnNine.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnNine.setText("9");
        jBtnNine.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnNineAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNineActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnNine, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 50, 50));

        jBtnPlus.setBackground(new java.awt.Color(255, 255, 255));
        jBtnPlus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnPlus.setText("+");
        jBtnPlus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnPlusAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 50, 50));

        jBtnSix.setBackground(new java.awt.Color(255, 255, 255));
        jBtnSix.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnSix.setText("6");
        jBtnSix.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnSixAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSixActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSix, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 50, 50));

        jBtnMul.setBackground(new java.awt.Color(255, 255, 255));
        jBtnMul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnMul.setText("*");
        jBtnMul.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnMulAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMulActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnMul, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 50, 50));

        jBtnThree.setBackground(new java.awt.Color(255, 255, 255));
        jBtnThree.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnThree.setText("3");
        jBtnThree.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnThreeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnThreeActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnThree, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 50, 50));

        jBtnEquals.setBackground(new java.awt.Color(255, 255, 255));
        jBtnEquals.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnEquals.setText("=");
        jBtnEquals.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnEqualsAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualsActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 50, 50));

        jBtnDot.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDot.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnDot.setText(".");
        jBtnDot.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnDotAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDotActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 50, 50));

        jBtnClear.setBackground(new java.awt.Color(255, 255, 255));
        jBtnClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnClear.setText("c");
        jBtnClear.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnClearAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, 50));

        jBtnBack.setBackground(new java.awt.Color(255, 255, 255));
        jBtnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Calculator/back_btn.png"))); // NOI18N
        jBtnBack.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnBackAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 50, 50));

        jBtnDiv.setBackground(new java.awt.Color(255, 255, 255));
        jBtnDiv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBtnDiv.setText("/");
        jBtnDiv.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jBtnDivAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jBtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 50, 50));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 270, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEightAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnEightAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEightAncestorAdded

    private void jBtnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEightActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnEight.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnEight.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnEightActionPerformed

    private void jBtnSevenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnSevenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSevenAncestorAdded

    private void jBtnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSevenActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnSeven.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnSeven.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnSevenActionPerformed

    private void jBtnFiveAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnFiveAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFiveAncestorAdded

    private void jBtnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFiveActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnFive.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnFive.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnFiveActionPerformed

    private void jBtnFourAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnFourAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnFourAncestorAdded

    private void jBtnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFourActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnFour.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnFour.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnFourActionPerformed

    private void jBtnTwoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnTwoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTwoAncestorAdded

    private void jBtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTwoActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnTwo.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnTwo.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnTwoActionPerformed

    private void jBtnOneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnOneAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOneAncestorAdded

    private void jBtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOneActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnOne.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnOne.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnOneActionPerformed

    private void jBtnPlusMinusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnPlusMinusAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPlusMinusAncestorAdded

    private void jBtnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusMinusActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(jTxtDisplay.getText()));
        ops = ops*(-1);
        jTxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtnPlusMinusActionPerformed

    private void jBtnZeroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnZeroAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnZeroAncestorAdded

    private void jBtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnZeroActionPerformed

    private void jBtnMinusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnMinusAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMinusAncestorAdded

    private void jBtnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMinusActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        Operations = "-";
    }//GEN-LAST:event_jBtnMinusActionPerformed

    private void jBtnNineAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnNineAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnNineAncestorAdded

    private void jBtnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNineActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnNine.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnNine.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnNineActionPerformed

    private void jBtnPlusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnPlusAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPlusAncestorAdded

    private void jBtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlusActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        Operations = "+";
    }//GEN-LAST:event_jBtnPlusActionPerformed

    private void jBtnSixAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnSixAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSixAncestorAdded

    private void jBtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSixActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnSix.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnSix.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnSixActionPerformed

    private void jBtnMulAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnMulAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMulAncestorAdded

    private void jBtnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMulActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        Operations = "*";
    }//GEN-LAST:event_jBtnMulActionPerformed

    private void jBtnThreeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnThreeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThreeAncestorAdded

    private void jBtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnThreeActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jTxtDisplay.getText();
        
        if(EnterNumber == ""){
            jTxtDisplay.setText(jBtnThree.getText());
        }
        else{
            EnterNumber = jTxtDisplay.getText() + jBtnThree.getText();
            jTxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtnThreeActionPerformed

    private void jBtnEqualsAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnEqualsAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEqualsAncestorAdded

    private void jBtnEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualsActionPerformed
        // TODO add your handling code here:
        String answer;
        secondNum = Double.parseDouble(jTxtDisplay.getText());
        
        if(Operations=="+"){
            result = firstNum + secondNum;
            answer = String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }
        else if(Operations=="-"){
            result = firstNum - secondNum;
            answer = String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }
        else if(Operations=="*"){
            result = firstNum*secondNum;
            answer = String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }
        else if(Operations=="/"){
            result = firstNum / secondNum;
            answer = String.format("%.2f", result);
            jTxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jBtnEqualsActionPerformed

    private void jBtnDotAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnDotAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDotAncestorAdded

    private void jBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDotActionPerformed
        // TODO add your handling code here:
        if(!jTxtDisplay.getText().contains(".")){
            jTxtDisplay.setText(jTxtDisplay.getText() + jBtnDot.getText());
        }
    }//GEN-LAST:event_jBtnDotActionPerformed

    private void jBtnClearAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnClearAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnClearAncestorAdded

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        // TODO add your handling code here:
        jTxtDisplay.setText("");
    }//GEN-LAST:event_jBtnClearActionPerformed

    private void jBtnBackAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnBackAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBackAncestorAdded

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        String BackSpace = null;
        
            if(jTxtDisplay.getText().length() > 0){
                StringBuilder strB = new StringBuilder(jTxtDisplay.getText());
                strB.deleteCharAt(jTxtDisplay.getText().length()-1);
                BackSpace = strB.toString();
                jTxtDisplay.setText(BackSpace);
            }
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void jBtnDivAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jBtnDivAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDivAncestorAdded

    private void jBtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jTxtDisplay.getText());
        jTxtDisplay.setText("");
        Operations = "/";
    }//GEN-LAST:event_jBtnDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnClear;
    private javax.swing.JButton jBtnDiv;
    private javax.swing.JButton jBtnDot;
    private javax.swing.JButton jBtnEight;
    private javax.swing.JButton jBtnEquals;
    private javax.swing.JButton jBtnFive;
    private javax.swing.JButton jBtnFour;
    private javax.swing.JButton jBtnMinus;
    private javax.swing.JButton jBtnMul;
    private javax.swing.JButton jBtnNine;
    private javax.swing.JButton jBtnOne;
    private javax.swing.JButton jBtnPlus;
    private javax.swing.JButton jBtnPlusMinus;
    private javax.swing.JButton jBtnSeven;
    private javax.swing.JButton jBtnSix;
    private javax.swing.JButton jBtnThree;
    private javax.swing.JButton jBtnTwo;
    private javax.swing.JButton jBtnZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtDisplay;
    // End of variables declaration//GEN-END:variables
}
